package com.ranx.model.Do;

import java.io.Serializable;
import java.util.Date;

public class OperateLogDo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.member_id
     *
     * @mbg.generated
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.log_content
     *
     * @mbg.generated
     */
    private String logContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.created_id
     *
     * @mbg.generated
     */
    private Long createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.created_name
     *
     * @mbg.generated
     */
    private String createdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.update_id
     *
     * @mbg.generated
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.update_name
     *
     * @mbg.generated
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate_log.valid
     *
     * @mbg.generated
     */
    private Integer valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operate_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.id
     *
     * @return the value of operate_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.id
     *
     * @param id the value for operate_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.member_id
     *
     * @return the value of operate_log.member_id
     *
     * @mbg.generated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.member_id
     *
     * @param memberId the value for operate_log.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.type
     *
     * @return the value of operate_log.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.type
     *
     * @param type the value for operate_log.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.log_content
     *
     * @return the value of operate_log.log_content
     *
     * @mbg.generated
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.log_content
     *
     * @param logContent the value for operate_log.log_content
     *
     * @mbg.generated
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.created_id
     *
     * @return the value of operate_log.created_id
     *
     * @mbg.generated
     */
    public Long getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.created_id
     *
     * @param createdId the value for operate_log.created_id
     *
     * @mbg.generated
     */
    public void setCreatedId(Long createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.created_name
     *
     * @return the value of operate_log.created_name
     *
     * @mbg.generated
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.created_name
     *
     * @param createdName the value for operate_log.created_name
     *
     * @mbg.generated
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName == null ? null : createdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.created_time
     *
     * @return the value of operate_log.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.created_time
     *
     * @param createdTime the value for operate_log.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.update_id
     *
     * @return the value of operate_log.update_id
     *
     * @mbg.generated
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.update_id
     *
     * @param updateId the value for operate_log.update_id
     *
     * @mbg.generated
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.update_name
     *
     * @return the value of operate_log.update_name
     *
     * @mbg.generated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.update_name
     *
     * @param updateName the value for operate_log.update_name
     *
     * @mbg.generated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.update_time
     *
     * @return the value of operate_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.update_time
     *
     * @param updateTime the value for operate_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate_log.valid
     *
     * @return the value of operate_log.valid
     *
     * @mbg.generated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate_log.valid
     *
     * @param valid the value for operate_log.valid
     *
     * @mbg.generated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }
}